---
- name: install snapd
  apt:
    name=snapd
    state=present
  become: yes

- name: Alias configuration
  # todo: change to /etc/profile.de
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} add snap to path "
    content: |
      PATH=$PATH:/snap/bin