---
- name: install snapd
  apt:
    name=snapd
    state=present
  become: yes

- name: Alias configuration
  lineinfile:
    create: yes
    path: '/etc/profile.d/snap.sh'
    line: 'PATH=$PATH:/snap/bin'
  become: true