---
- name: pip
  apt:
    name: python-pip
    state: latest
  become: yes

- name: pip3
  apt:
    name: python3-pip
    state: latest
  become: yes

- name: ansible
  pip:
    name: ansible
  become: yes

- name: build tools
  apt:
    name: autoconf,make
    state: latest
  become: yes

- name: standart desktop tools
  apt:
    name: ubuntu-desktop
    state: latest
  become: yes
  tags: no_ci

- name: python3.7
  apt:
    name: python3.7
    state: latest
  become: yes

- name: python3.7 venv
  apt:
    name: python3.7-venv
    state: latest
  become: yes

- name: zip programs
  apt:
    name: rar,unrar,unzip
    state: latest
  become: yes
