---

- name: ansible
  apt:
    name: ansible
    state: latest
  register: installation
  become: yes

- name: build tools
  apt:
    name: autoconf,make
    state: latest
  register: installation
  become: yes

- name: python3.6
  apt:
    name: python3.6
    state: latest
  register: installation
  become: yes

- name: python3.7
  apt:
    name: python3.7
    state: latest
  register: installation
  become: yes

- name: pip
  apt:
    name: python-pip
    state: latest
  register: installation
  become: yes

- name: pip3
  apt:
    name: python3-pip
    state: latest
  register: installation
  become: yes
