---
- name: pip
  apt:
    name: python-pip
    state: latest
  become: yes

- name: ansible
  pip:
    name: ansible
  become: yes

- name: build tools
  apt:
    name: autoconf,make,cmake
    state: latest
  become: yes

- name: standart desktop tools
  apt:
    name: ubuntu-desktop
    state: latest
  become: yes
  tags: no_ci

- name: zip programs
  apt:
    name: rar,unrar,unzip
    state: latest
  become: yes
