---
- name: Check if Python {{ item }} already exists
  stat:
    path: "/usr/local/python-{{ item }}"
  register: stat_result

- name: Installing Python {{ item }} from source
  block:
  - name: Download sources of Python {{ item }}
    unarchive:
      src: https://www.python.org/ftp/python/{{ item }}/Python-{{ item }}.tar.xz
      dest: /tmp/
      remote_src: yes

  - name: Configure
    shell: "./configure --prefix=/usr/local/python-{{ item }}"
    args:
      chdir: /tmp/Python-{{ item }}

  - name: Make
    shell: "make -j 4"
    args:
      chdir: /tmp/Python-{{ item }}

  - name: Install
    shell: "make altinstall"
    args:
      chdir: /tmp/Python-{{ item }}
    become: yes

  - name: Remove Sources
    file:
      path: /tmp/Python-{{ item }}
      state: absent
    become: yes

  when: stat_result.stat.exists == False
