---
- name: Check if terraform exists
  stat:
    path: /usr/local/bin/python3
  register: check_custom_python_exists

- name: retrive installed version of python
  shell: "python3 --version | grep 'Python ' | sed 's/Python //' | tr -d '\n'"
  changed_when: False
  register: python_installed_version

- name: Display python versions
  debug: msg='installed python version is {{ python_installed_version.stdout }}, version should be {{ python_version }}!'

- name: Installing Python from source
  block:
  - name: Install required software
    apt:
      name: build-essential,tk-dev,libncurses5-dev,libncursesw5-dev,libreadline6-dev,libdb5.3-dev,libgdbm-dev,libsqlite3-dev,libssl-dev,libbz2-dev,libexpat1-dev,liblzma-dev,zlib1g-dev,libffi-dev
      state: latest
    become: yes

  - name: Download sources
    unarchive:
      src: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz
      dest: /tmp/
      remote_src: yes

  - name: Configure
    shell: "./configure --prefix=/usr/local/opt/python-{{ python_version }}"
    args:
      chdir: /tmp//Python-{{ python_version }}

  - name: Make
    shell: "make -j 4"
    args:
      chdir: /tmp//Python-{{ python_version }}

  - name: Install
    shell: "make altinstall"
    args:
      chdir: /tmp//Python-{{ python_version }}
    become: yes

  - name: Make Symlinks
    file:
      src: "/usr/local/opt/python-{{ python_version }}/bin/{{ item }}{{ python_version[:3] }}"
      dest: "/usr/bin/{{ item }}{{ python_version[:3] }}"
      state: link
    loop:
      - pydoc
      - python
      - pyvenv-
      - pip
    become: yes

  when: check_custom_python_exists.stat.exists == false or
    python_installed_version.stdout not in python_version
