- name: Install required software
  apt:
    name: build-essential,tk-dev,libncurses5-dev,libncursesw5-dev,libreadline6-dev,libdb5.3-dev,libgdbm-dev,libsqlite3-dev,libssl-dev,libbz2-dev,libexpat1-dev,liblzma-dev,zlib1g-dev,libffi-dev
    state: latest
  become: yes

- name: Install all current Python versions
  include: install_local_python.yml
  with_items:
    - 3.8.0
    - 3.7.4
    - 3.6.8
    - 3.5.7
    - 2.7.16