---
- name: Check if terraform exists
  stat:
    path: /usr/local/bin/python3
  register: check_custom_python_exists

- name: retrive installed version of python
  shell: "python3 --version | grep 'Python ' | sed 's/Python //' | tr -d '\n'"
  changed_when: False
  register: python_installed_version

- name: Display python versions
  debug: msg='installed python version is {{ python_installed_version.stdout }}, version should be {{ python_version }}!'

- name: Installing Python from source
  block:
    - name: Doing stuff
      debug: msg='Doing'
  when: check_custom_python_exists.stat.exists == false or
    python_installed_version.stdout not in python_version
