---
block:
# repair https://stackoverflow.com/questions/40877643/apt-get-install-in-ubuntu-16-04-docker-image-etc-resolv-conf-device-or-reso:
tags: no_ci
  - name: install resolv conv
    apt:
      name: resolvconf
      state: present
    become: yes

  - name: enable resolv conv service
    systemd:
      name: resolvconf.service
      state: started
      enabled: yes
    become: yes
    tags: no_ci