- hosts: localhost
  roles:
    - {role: catacomb, tags: catacomb}
    - {role: googler, tags: googler}
    - imgcat
    - rdesktop
    #- scc later ... I have to learn some stuff about go package management
    - wptools