- hosts: thebotpi
  roles:
    - apt_update
    - bot_ws_thebotit
    - role: bot_python_from_source
      python_version: "3.8.2"
    - role: geerlingguy.ntp
      ntp_timezone: Europe/Berlin
      become: yes
      tags: no_ci
    - bot_pi-hole
    - bot_jupyter