---
- name: install virtual box
  apt:
    name: virtualbox,virtualbox-qt,virtualbox-dkms
    state: latest
  register: installation
  become: yes

- name: install vagrant
  apt:
    name: vagrant
    state: latest
  register: installation
  become: yes
