---
- name: Cron Entry for the nightly run
  cron:
    name: "run bot it"
    minute: "0"
    hour: "0"
    job: "/home/pi/WS_THEbotIT/scripts/starter.sh >> /home/pi/.wiki_bot/cron.log 2>&1"
  tags: no_ci

- name: Read Origin
  shell: "git remote -v"
  args:
    chdir: "~/WS_THEbotIT"
  register: remote_out

- name: Change Origin
  shell: "git remote set-url origin git@github.com:the-it/WS_THEbotIT.git"
  args:
    chdir: "~/WS_THEbotIT"
  when: "git@github.com:the-it/WS_THEbotIT.git" not in remote_out.stdout
