---
- name: Cron Entry for the nightly run
  cron:
    name: "run bot it"
    minute: "0"
    hour: "0"
    job: "/home/pi/WS_THEbotIT/scripts/starter.sh >> /home/pi/.wiki_bot/cron.log 2>&1"
  tags: no_ci