---
- name: install thunderbird
  apt:
    name: thunderbird
    state: latest
  register: installation
  become: yes

- name: install lightning
  apt:
    name: xul-ext-lightning
    state: latest
  register: installation
  become: yes

- name: add to autostart
  include_role:
    name: auto_start
  vars:
    program: thunderbird
    exec: /usr/bin/thunderbird