---
- include_vars: password.yml

- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation
  become: yes

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation is success
  register: cloning
  become: no

- name: Check that the ~/.zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_result

- name: Check whether .zshrc is original
  command: awk /ZSH_THEME=\"robbyrussell\"/ ~/.zshrc
  register: checkoriginalzshrc
  changed_when: False
  when: stat_result.stat.exists == True

- name: Creating new ~/.zshrc
  copy:
    content: ""
    dest: ~/.zshrc
    force: yes
  when: stat_result.stat.exists == False or checkoriginalzshrc.stdout is match("ZSH_THEME=\"robbyrussell\"")
  become: no

- name: Basic configuration
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} Basic Config "
    content: |
      export ZSH=~/.oh-my-zsh
      ZSH_THEME="ys"
      plugins=(git)
      source $ZSH/oh-my-zsh.sh

- name: Alias configuration
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} Aliases "
    content: |
      loc() { find "$*" -type f -name '*'| xargs wc -l ; }

- name: Check whether zsh is already standard shell
  command: echo $SHELL
  register: existing_shell
  changed_when: False

- name: Change Shell to Zsh
  expect:
    command: "chsh -s /bin/zsh"
    responses:
      (?i)password: "{{ user_password }}"
  when: existing_shell.stdout is not match("/bin/zsh")
