---
- name: install libssl1.0-dev
  apt:
    name: libssl1.0-dev
    state: present
  register: installation
  become: yes

- name: install nodejs-dev
  apt:
    name: nodejs-dev
    state: present
  register: installation
  become: yes

- name: install node-gyp
  apt:
    name: node-gyp
    state: present
  register: installation
  become: yes

- name: install npm
  apt:
    name: npm
    state: present
  register: installation
  become: yes
