---
- name: enable nightlight
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enable"
    value: "true"
    state: present

- name: set from time
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
    value: "20.0"
    state: present

- name: set temperature
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
    value: "uint32 4061"
    state: present
