---
- name: put systemd unit file in place
  template:
    src: templates/docker_compose.service
    dest: "/usr/lib/systemd/user/{{ service_name }}_docker_compose.service"
  become: yes

- name: enable and restart systemd service
  systemd:
    name: "{{ service_name }}_docker_compose.service"
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes


