---
- name: install visual studio code
  tags: no_ci
  import_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username:  "{{ ansible_env.USER  }}"
        visual_studio_code_extensions:
          - dbaeumer.vscode-eslint
          - blanu.vscode-styled-jsx
          - christian-kohler.npm-intellisense
          - christian-kohler.path-intellisense
          - cmstead.jsrefactor
          - CoenraadS.bracket-pair-colorizer
          - DigitalBrainstem.javascript-ejs-support
          - dsznajder.es7-react-js-snippets
          - ecmel.vscode-html-css
          - EditorConfig.EditorConfig
          - emilast.LogFileHighlighter
          - eg2.vscode-npm-script
          - esbenp.prettier-vscode
          - formulahendry.auto-close-tag
          - formulahendry.auto-rename-tag
          - jpoissonnier.vscode-styled-components
          - leizongmin.node-module-intellisense
          - mariusschulz.yarn-lock-syntax
          - mhutchie.git-graph
          - mikestead.dotenv
          - mohd-akram.vscode-html-format
          - mrmlnc.vscode-scss
          - msjsdiag.debugger-for-chrome
          - OfHumanBondage.react-proptypes-intellisense
          - sleistner.vscode-fileutils
          - stuart.unique-window-colors
          - vscode-icons-team.vscode-icons
          - yzhang.markdown-all-in-one
          - Zignd.html-css-class-completion

- name: force write settings
  copy:
    src: files/settings.json
    dest: "{{ lookup('env','HOME') }}/.config/Code/User/settings.json"
    force: yes