---
- name: install visual studio code
  tags: no_ci
  import_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username:  "{{ ansible_env.USER  }}"
        visual_studio_code_extensions:
          - blanu.vscode-styled-jsx
          - christian-kohler.npm-intellisense
          - christian-kohler.path-intellisense
          - cmstead.jsrefactor
          - CoenraadS.bracket-pair-colorizer
          - dbaeumer.vscode-eslint
          - DigitalBrainstem.javascript-ejs-support
          - donjayamanne.githistory
          - dsznajder.es7-react-js-snippets
          - ecmel.vscode-html-css
          - EditorConfig.EditorConfig
          - emilast.LogFileHighlighter
          - eg2.vscode-npm-script
          - Equinusocio.vsc-material-theme
          - esbenp.prettier-vscode
          - formulahendry.auto-close-tag
          - formulahendry.auto-rename-tag
          - jpoissonnier.vscode-styled-components
          - leizongmin.node-module-intellisense
          - mikestead.dotenv
          - mohd-akram.vscode-html-format
          - mrmlnc.vscode-scss
          - msjsdiag.debugger-for-chrome
          - OfHumanBondage.react-proptypes-intellisense
          - PKief.material-icon-theme
          - sleistner.vscode-fileutils
          - stuart.unique-window-colors
          - vscode-icons-team.vscode-icons
          - yzhang.markdown-all-in-one
          - Zignd.html-css-class-completion
        visual_studio_code_settings: {
          "editor.rulers": [80, 100, 120],
          "editor.renderWhitespace": true,
          "files.associations": {
            "Vagrantfile": "ruby"
          }
        }
