---
### add the aws-client

- name: awscli
  become: true   
  apt:
    name=awscli
    state=present
        
### create crendentials for aws

- name: Check if ~/.aws path exists
  stat: path=~/.aws
  register: check_aws_config_path

- name: mkdir for aws credentials
  file:
    path: ~/.aws
    state: directory
  when: check_aws_config_path.stat.exists == false
    
- name: add credentials file
  ignore_errors: yes
  template:
        src: files/credentials
        dest: ~/.aws/
  when: check_aws_config_path.stat.exists == false
  
- name: add config file
  ignore_errors: yes
  template:
    src: files/config
    dest: ~/.aws/
  when: check_aws_config_path.stat.exists == false