---
- name: install docker
  apt:
    name: docker.io
  become: true

- name: Add docker group
  group:
    name: docker
    system: yes
  become: true

- name: Ensure docker users are added to the docker group.
  user:
    name: "erik"
    groups: docker
    append: true
  become: true