---
- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: Create venv and install requirements
  pip:
    requirements: "{{ lookup('env','HOME') }}/workspace/WS_THEbotIT/requirements.txt"
    virtualenv: "{{ lookup('env','HOME') }}/workspace/WS_THEbotIT/venv"
    virtualenv_python: "/usr/local/python-3.8.2/bin/python3.8"
  tags:
    - venv
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.local/bin"

- name: env for development
  copy:
    content: |
      export WS_REAL_WIKI=TRUE
      export WS_REAL_DATA=TRUE
    dest: /etc/profile.d/ws_the_bot_it.sh
  become: yes
