---
- name: Install nfs tools
  apt:
    name: nfs-common
  become: yes

- name: Create mount points for {{ item }}
  file:
    path: '/mnt/{{ item }}'
    state: directory
    mode: '0755'
    owner: "esommer"
  become: yes

- name: mount nas directories for {{ item }}
  mount:
    path: '/mnt/{{ item }}'
    src: '192.168.178.11:/volume1/{{ item }}'
    fstype: nfs
    state: mounted
  become: yes
  tags: no_ci