---
- name: Install jmespath
  apt:
    name: python3-jmespath
    state: latest
  become: yes

- name: Jetbrains Toolbox
  block:
    - name: libfuse2
      apt:
        name: libfuse2
        state: latest
      register: installation
      become: yes

    - name: install toolbox
      import_role:
        name: jaredhocutt.jetbrains_toolbox
  tags: no_ci
